const songData = [
  {
    spotifyId: "sptf1",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    image: "https://headlinerhub.com/assets/image-cache/img/articles//crops/Small.d2f144bd.theweeknd_blinding_lights.65d63dff.jpg",
  },
  {
    spotifyId: "sptf2",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    image: "https://upload.wikimedia.org/wikipedia/en/b/b4/Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png",
  },
  {
    spotifyId: "sptf3",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    image: "https://i.scdn.co/image/ab67616d0000b2734bc66095f8a70bc4e6593f4f",
  },
  {
    spotifyId: "sptf4",
    title: "Bad Guy",
    artist: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    image: "https://news.utexas.edu/wp-content/uploads/2019/11/Joker-600x400-c-default.jpg",
  },
  {
    spotifyId: "sptf5",
    title: "Stay",
    artist: "The Kid LAROI, Justin Bieber",
    album: "F*CK LOVE 3: OVER YOU",
    image: "https://i.scdn.co/image/ab67616d0000b27341e31d6ea1d493dd77933ee5",
  },
  {
    spotifyId: "sptf6",
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    image: "https://i.ytimg.com/vi/Qfm6nfz1QNQ/sddefault.jpg",
  },
  {
    spotifyId: "sptf7",
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
    image: "https://static-cse.canva.com/blob/2031583/1600w-fxYFTKLArdY.jpg",
  },
  {
    spotifyId: "sptf8",
    title: "Dance Monkey",
    artist: "Tones and I",
    album: "The Kids Are Coming",
    image: "https://static-cse.canva.com/blob/2031583/1600w-fxYFTKLArdY.jpg",
  },
  {
    spotifyId: "sptf9",
    title: "Peaches",
    artist: "Justin Bieber",
    album: "Justice",
    image: "https://static-cse.canva.com/blob/2031583/1600w-fxYFTKLArdY.jpg",
  },
  {
    spotifyId: "sptf10",
    title: "Montero (Call Me By Your Name)",
    artist: "Lil Nas X",
    album: "MONTERO",
    image: "https://static-cse.canva.com/blob/2031583/1600w-fxYFTKLArdY.jpg",
  },

  {
    spotifyId: "sptf11",
    title: "Espresso",
    artist: "Sabrina Carpenter",
    album: "Short n’ Sweet",
    image: "https://i.scdn.co/image/ab67616d0000b273a3c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf12",
    title: "Beautiful Things",
    artist: "Benson Boone",
    album: "Fireworks & Rollerblades",
    image: "https://i.scdn.co/image/ab67616d0000b273b3c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf13",
    title: "BIRDS OF A FEATHER",
    artist: "Billie Eilish",
    album: "HIT ME HARD AND SOFT",
    image: "https://i.scdn.co/image/ab67616d0000b273c3c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf14",
    title: "Gata Only",
    artist: "FloyyMenor, Cris MJ",
    album: "Gata Only - Single",
    image: "https://i.scdn.co/image/ab67616d0000b273d3c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf15",
    title: "Lose Control",
    artist: "Teddy Swims",
    album: "I've Tried Everything But Therapy (Part 1)",
    image: "https://i.scdn.co/image/ab67616d0000b273e3c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf16",
    title: "End Of Beginning",
    artist: "Djo",
    album: "DECIDE",
    image: "https://i.scdn.co/image/ab67616d0000b273f3c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf17",
    title: "Too Sweet",
    artist: "Hozier",
    album: "Unreal Unearth",
    image: "https://i.scdn.co/image/ab67616d0000b273a4c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf18",
    title: "One Of The Girls",
    artist: "The Weeknd, JENNIE, Lily-Rose Depp",
    album: "The Idol Episode 4 (Music from the HBO Original Series)",
    image: "https://i.scdn.co/image/ab67616d0000b273b4c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf19",
    title: "Cruel Summer",
    artist: "Taylor Swift",
    album: "Lover",
    image: "https://i.scdn.co/image/ab67616d0000b273c4c3e3e3e3e3e3e3e3e3e3e3",
  },
  {
    spotifyId: "sptf20",
    title: "Die With A Smile",
    artist: "Bruno Mars, Lady Gaga",
    album: "Die With A Smile - Single",
    image: "https://i.scdn.co/image/ab67616d0000b273d4c3e3e3e3e3e3e3e3e3e3e3",
  },
];

export default songData;
